DigiShop/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DigiKalaShop.SysCoreServices.PropellantServices.CoreAttributes;
using DigiKalaShop.ViewModels.OTP;
using DigiShop.CoreBussiness.EfCoreDomains.AccessPermissions;
using DigiShop.CoreBussiness.EfCoreDomains.SiteSettings;
using DigiShop.CoreBussiness.RepsPattern;
using DigiShop.ViewModels.Manager;
using Mapster;
using MapsterMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace DigiShop.Controllers
{
    [Authorize]
    public class ManagerController:Controller
    {
        private IUnitOfWork _work;
        private IMapper _mapper;
        private ISetSettings _settings;
        private IAccessPermissionService _accessPermissionService;
        private readonly ILogger<ManagerController> _logger;
        public ManagerController(IUnitOfWork work, IMapper mapper, ISetSettings settings, IAccessPermissionService accessPermissionService,ILogger<ManagerController> logger)
        {
            _work = work;
            _mapper = mapper;
            _settings = settings;
            _logger = logger;
            _accessPermissionService = accessPermissionService;
        }
        
        [HttpGet]
        public async Task<IActionResult> AddSiteSetting(string ?Message,bool? IsCompleted)
        {
            var setting = new SettingViewModel()
            {
                Message = Message, IsCompleted = IsCompleted
            };
            return View(setting);
        }
        [HttpPost]
        public async Task<IActionResult> AddSiteSetting(SettingViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var setting = new SiteSetting();
                    _mapper.Map(model, setting);
                    await _settings.AddSettingAsync(setting);
                    var row = await _work.SaveChangesAsync();
                    if (row > 0)
                    {
                        model.IsCompleted = true;
                        model.Message = "تنظیمات اضافه شد";
                        return RedirectToAction("AddSiteSetting",new {Message =model.Message,IsCompleted = model.IsCompleted });
                    }
                    model.IsCompleted = false;
                    model.Message = "خطا در پاسخگویی";
                    return RedirectToAction("AddSiteSetting",new {Message =model.Message,IsCompleted = model.IsCompleted });
                }
                catch (Exception e)
                {
                   _logger.LogError(e.Message,e);
                }
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> ModifySetting(string ?Message,bool?IsCompleted, int id =1)
        {
            var setting = await _settings.GetSiteSettingAsync(id);
            var data = setting.Adapt<ModifySettingViewModel>();
            data.Message = Message;
            data.IsCompleted = IsCompleted;
            return View(data);
        }
        [HttpPost]
        public async Task<IActionResult> ModifySetting(ModifySettingViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var setting = await _settings.GetSiteSettingAsync(1);
                    _mapper.Map(model, setting);
                    var row = await _work.SaveChangesAsync();
                    if (row > 0)
                    {
                        model.IsCompleted = true;
                        model.Message = "تغییرات اعمال شد";
                        return RedirectToAction("ModifySetting",new {Message =model.Message,IsCompleted = model.IsCompleted });
                    }
                    model.IsCompleted = false;
                    model.Message = "خطا در پاسخگویی";
                    return RedirectToAction("ModifySetting",new {Message =model.Message,IsCompleted = model.IsCompleted });
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message,e);
                }
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddPermission()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddPermission(AddPermissionViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _accessPermissionService.IsPermissionExistsAsync(model.Permission);
                    if (result)
                    {
                        ModelState.AddModelError(nameof(model.Permission),"این دسترسی در سیستم وجود دارد");
                        return View(model);
                    }
                    var permission = new Permission();
                    permission.permission = model.Permission;
                    await _accessPermissionService.AddPermissionAsync(permission);
                    var row = await _work.SaveChangesAsync();
                    if (row > 0)
                    {
                        model.IsCompleted = true;
                        model.Message = "با موفقیت اضافه شد";
                        return View(model);
                    }
                    model.IsCompleted = false;
                    model.Message = "خطا در پاسخگویی";
                    return View(model);
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message,e);
                }
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> ModifyPermission(int id)
        {
            var permission = await _accessPermissionService.GetPermissionAsync(id);
            var data = new ModifyPermissionViewModel()
            {
                Permission = permission.permission,
                id = permission.id
            };
            return View(data);
        }
        [HttpPost]
        public async Task<IActionResult> ModifyPermission(ModifyPermissionViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var permission = await _accessPermissionService.GetPermissionAsync(model.id);
                    permission.permission = model.Permission;
                    var row = await _work.SaveChangesAsync();
                    if (row > 0)
                    {
                        model.IsCompleted = true;
                        model.Message = "با موفقیت تغییر کرد";
                        return View(model);
                    }
                    model.IsCompleted = false;
                    model.Message = "خطا در پاسخگویی";
                    return View(model);
                }
                catch (Exception e)
                {
                  _logger.LogError(e.Message,e);
                }
              
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(AddRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _accessPermissionService.IsRoleExistsAsync(model.rolename);
                    if (result)
                    {
                        ModelState.AddModelError(nameof(model.rolename),"این نقش در سیستم وجود دارد");
                        return View(model);
                    }
                    var role = new Role();
                    role.rolename = model.rolename;
                    await _accessPermissionService.AddRoleASync(role);
                    var row = await _work.SaveChangesAsync();
                    if (row > 0)
                    {
                        model.IsCompleted = true;
                        model.Message = "با موفقیت اضافه شد";
                        return View(model);
                    }
                    model.IsCompleted = false;
                    model.Message = "خطا در پاسخگویی";
                    return View(model);
                }
                catch (Exception e)
                {
                   _logger.LogError(e.Message,e);
                }
              
            }
            return View(model);
        }
        
        [HttpGet]
        public async Task<IActionResult> ModifyRole(int? id)
        {
            var role = await _accessPermissionService.GetRoleAsync(id.Value);
            if (role == null)
            {
                return RedirectToAction("ModifyRole", new {id = 0});
            }
            var data = new ModifyRoleViewModel()
            {
                id = role.id,
                rolename = role.rolename
            };
            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> ModifyRole(ModifyRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var role = await _accessPermissionService.GetRoleAsync(model.id);
                    role.rolename = model.rolename;
                    var row = await _work.SaveChangesAsync();
                    if (row > 0)
                    {
                        model.IsCompleted = true;
                        model.Message = "با موفقیت اضافه شد";
                        return View(model);
                    }
                    model.IsCompleted = false;
                    model.Message = "خطا در پاسخگویی";
                    return View(model);
                }
                catch (Exception e)
                {
                 _logger.LogError(e.Message,e);
                }
            }

DigiShop/Controllers/StoreController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using DigiKalaShop.SysCoreServices.AuthenticationServices;
using DigiKalaShop.ViewModels.Stores;
using DigiShop.CoreBussiness.EfCoreDomains.AccessPermissions;
using DigiShop.CoreBussiness.EfCoreDomains.OTP;
using DigiShop.CoreBussiness.EfCoreDomains.Stores;
using DigiShop.CoreBussiness.EfCoreDomains.Users;
using DigiShop.CoreBussiness.RepsPattern;
using DigiShop.InfraStructure.KaveNegar.SmsPanelService;
using DigiShop.StorageService.Migrations;
using DigiShop.SysCoreServices.FileHandlers;
using MapsterMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage;
using Serilog;

namespace DigiShop.Controllers
{
    public class StoreController:Controller
    { 
        private IUnitOfWork _work;
        private IAccountService _accountService;
        private IMapper _mapper;
        private IOtpService _otpService;
        private IMessageService _messageService;
        private IAccessPermissionService _accessPermissionService;
        private IStoreService _storeService;
        private IWebHostEnvironment _environment;
        private IFileManager _fileManager;
        public StoreController(IUnitOfWork work, IAccountService accountService, IMapper mapper, IOtpService otpService, IMessageService messageService, IAccessPermissionService accessPermissionService, IStoreService storeService, IWebHostEnvironment environment, IFileManager fileManager)
        {
            _work = work;
            _accountService = accountService;
            _mapper = mapper;
            _otpService = otpService;
            _messageService = messageService;
            _accessPermissionService = accessPermissionService;
            _storeService = storeService;
            _environment = environment;
            _fileManager = fileManager;
        }
        public async Task SendActivationCode(string code,string recptor)
        {
            await _messageService.SendMessageAsync("Digishop", recptor, code);
        }
        [HttpGet]
        public async Task<IActionResult> SignupStore()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SignupStore(SignupStoreViewModel model)
        {
            if (ModelState.IsValid)
            { 
                var IsemailExists = await _storeService.IsEmailExistsAsync(model.Mail);
                if (IsemailExists)
                {
                    ModelState.AddModelError(nameof(model.Mail),"ایمیل وجود دارد ...");
                    return View(model);
                }
                var userId = 0;
                var result = await _accountService.IsPhonenumberExistsAsync(model.Phonenumber);
                if (result)
                {
                   await _accessPermissionService.UpdateRoleAsync(model.Phonenumber);
                   userId = _accountService.GetUserIdAsync(model.Phonenumber);
                   await _work.SaveChangesAsync();
                }
                else
                {
                    var user = new User()
                    {
                        Phonenumber = model.Phonenumber,
                        roleId = _accessPermissionService.SearchRoleAsync(model.fixedrole),
                        NationalCode = null,
                        Password = _accountService.GenerateHash(model.Password),
                        UserStatus = UserStatus.None,
                        IsRulesAccepted = model.IsRuleAccepted
                    };
                    await _accountService.SignupUserAsync(user);
                    await _work.SaveChangesAsync();
                    userId = user.id;
                }
                var store = new Store()
                {
                    Address = "null", Logo = "null", Mail = model.Mail, Description = "null", StoreName = "null",
                    StoreStatus = StoreStatus.None, Telephone = "null", IsMailActive = false, IsPhonenumberActive = false,
                    UserId = userId
                };
                await _storeService.AddNewStoreAsync(store);
                var row = await _work.SaveChangesAsync();
                if (row > 0)
                {
                    model.IsCompleted = true;
                    model.Message = "کاربر محترم فروشگاه شما ثبت گردید . لطفا برای کامل کردن اطلاعات فروشگاه خود اقدام فرمایید";
                    return View(model);
                }
                model.IsCompleted = false;
                model.Message = "خطا در پاسخگویی";
                return View(model);
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> StoreCompletor()
        {
            var store = await _storeService.GetStoreAsync(User.GetCurrentUserId());
            var datastore = new StoreCompletorViewModel() {id =User.GetCurrentUserId(), Address = store.Address, Description = store.Address, Mail = store.Mail, Telephone = store.Telephone, StoreName = store.StoreName,IsRuleAccepted = store.IsRuleAccepted};
            return View(datastore);
        }
        [HttpPost]
        public async Task<IActionResult> StoreCompletor(StoreCompletorViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var store = await _storeService.GetStoreAsync(User.GetCurrentUserId());
                    store.Address = model.Address;
                    store.Description = model.Description;
                    store.Logo = null;
                    store.Mail = model.Mail;
                    store.Telephone = model.Telephone;
                    store.StoreName = model.StoreName;
                    store.IsRuleAccepted = model.IsRuleAccepted;
                    if (Path.GetExtension(model.file.FileName) == ".JPG" || Path.GetExtension(model.file.FileName) == ".jpg")
                    {
                        await _fileManager.UploadImageAsync(_environment, "Images", "Document", model.file, store.UserId);
                    }
                    else
                    {
                        ModelState.AddModelError(nameof(model.file),"فقط فایل با پسوند jpg قبول میشود");
                        return View(model);
                    }
                    var row = await _work.SaveChangesAsync();
                    if (row > 0)
                    {
                        model.IsCompleted = true;
                        model.Message = "اطلاعات فروشگاه شما با موفقیت ثبت شد"; 
                        return RedirectToAction("DashBoard", "Admin",new {Message = model.Message,IsCompleted = model.IsCompleted});
                    }
                    model.IsCompleted = false;
                    model.Message = "خطا در پاسخگویی";
                    return View(model);
                }
                catch (Exception e)
                {
                    Log.Logger.Error(e.Message,e);
                }
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Download()
        {
            try
            {
                var data = await _fileManager.DownloadImageAsync(_environment,"Images","Document",User.GetCurrentUserId());
                return File(data, "Image/jpg");
            }
            catch (Exception e)
            {
                Log.Logger.Error(e.Message,e);
            }
            return BadRequest();
        }

        public async Task<IActionResult> print()
        {
            return View();
        }
    }
}

DigiShop/Views/Shared/AuthAccount.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/Account.css">
    <link rel="stylesheet" href="~/fontawesome-free-5.15.4-web/css/fontawesome.min.css">
    <link rel="stylesheet" href="~/font-awesome-4.7.0/font-awesome-4.7.0/css/font-awesome.min.css">
</head>
<body>
<header>

</header>

<div class="container-fluid">
    <div class="row margin-top-50">
        <div class="col-md-6 col-sm offset-4 col-sm-4 col-md offset-4 col-sm-4 col-sm offset-4 col-xl-offset-3 col-xl-5-offset-5 loginbox">
            <main>@RenderBody()</main>
        </div>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DigiShop/Views/Shared/ManualPannel.cshtml
@using System.Security.Claims
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/Account.css">
    <link rel="stylesheet" href="~/css/ManualPannel.css">
    <link rel="stylesheet" href="~/fontawesome-free-5.15.4-web/css/fontawesome.min.css">
    <link rel="stylesheet" href="~/font-awesome-4.7.0/font-awesome-4.7.0/css/font-awesome.min.css">
   
    <title>ManualPannel</title>
</head>
<body>


<div class="page-wrapper chiller-theme toggled">

<a href="#" id="show-sidebar" class="btn btn-sm btn-dark">
    <i class="fa fa-bars"></i>
</a>

<nav id="sidebar" class="sidebar-wrapper">

<div class="sidebar-content">

<div class="sidebar-brand">

    <a href="#">پنل مدیریتی دیجی شاپ</a>

    <div id="close-sidebar" style="padding: 10px;margin-left: 20px">
        <i class="fa fa-times"></i>
    </div>
</div>

<div class="sidebar-header">
    <img src="@Url.Action("Download","Store")"  style="background-position: center;background-size: cover;border-radius: 45px;height: 100px;width: 100px">
    <div class="user-info">

        <span class="user-name">
            <p style="color: white"><h7>@User.Claims.First(c=>c.Type == ClaimTypes.Name).Value</h7></p>
        </span>
        <span class="user-role">
            <p style="color: white"><h7>@User.Claims.First(c=>c.Type == ClaimTypes.Role).Value</h7></p>
        </span>
        <span class="user-status">
            <i class="fa fa-circle"></i>
            <span>آنلاین</span>
        </span>
    </div>
    <div class="user-pic">
        @if (User.IsInRole("manager"))
        {
          
        }
        else
        {

        }
    </div>
    
</div>

<div class="sidebar-menu">
<ul>

    @if (User.IsInRole("manager") || User.IsInRole("admin"))
    {
        <li class="sidebar-dropdown">
            <a href="#">
                <span class="pull-right">کاربران</span>
                <span class="pull-left fa fa-users"></span>
            </a>
            <div class="sidebar-submenu">
                <ul>
                    <li>
                        <a href="#">
                            مشتریان
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("SellerList","Admin")">
                            فروشندگان
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("StoreList","Admin")">
                            فروشگاه ها
                        </a>
                    </li>
                    <li>
                        <a href="/Admin/ShowStoreCategories">
                            انتظار
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="sidebar-dropdown">
            <a href="#">
                <span class="pull-right">محصولات</span>
                <span class="pull-left fa fa-th-list"></span>
            </a>
            <div class="sidebar-submenu">
                <ul>
                    <li>
                        <a href="@Url.Action("ShowCategoryHead","Admin")">
                            سردسته ها
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("SubCategory","Admin")">
                            برند ها
                        </a>
                    </li>
                    <li>
                        <a href="/Admin/ShowFields/">
                            مشخصه ها
                        </a>
                    </li>
                    <li>
                        <a href="/Admin/ShowAllProducts/">
                            نمایش محصولات
                        </a>
                    </li>
                </ul>
            </div>
        </li>

        <li class="sidebar-dropdown">
            <a href="#">
                <span class="pull-right">تبلیغات</span>
                <span class="pull-left fa fa-image"></span>
            </a>
            <div class="sidebar-submenu">
                <ul>
                    <li>
                        <a href="/Admin/ShowSliders">
                            اسلایدر
                        </a>
                    </li>
                    <li>
                        <a href="/Admin/ShowBanners">
                            جایگاه ها
                        </a>
                    </li>
                </ul>
            </div>
        </li>

        <li class="sidebar-dropdown">
            <a href="#">
                <span class="pull-right">مالی</span>
                <span class="pull-left fa fa-money"></span>
            </a>
            <div class="sidebar-submenu">
                <ul>
                    <li>
                        <a href="/Admin/ShowAllCoupons">
                            کوپن ها
                        </a>
                    </li>
                </ul>
            </div>
        </li>

        <li class="sidebar-dropdown">
            <a href="#">
                <span class="pull-right">تنظیمات</span>
                <span class="pull-left fa fa-cogs"></span>
            </a>
            <div class="sidebar-submenu">
                <ul>
                    <li>
                        <a href="@Url.Action("ManageRoleAccess","Manager")">
                            مدیریت نقش و دسترسی
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("AddSiteSetting", "Manager")">
                            اضافه سازی تنظیمات سایت
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("ModifySetting", "Manager")">
                            ویرایش تنظیمات سایت
                        </a>
                    </li>
                </ul>
            </div>
        </li>
    }
    else 
    {
        <li class="sidebar-dropdown">
            <a href="#">
                <span class="pull-right">محصولات</span>
                <span class="pull-left fa fa-barcode"></span>
            </a>
            <div class="sidebar-submenu">
                <ul>
                    <li>
                        <a href="/Panel/ShowBrands">
                            برند ها
                        </a>
                    </li>
                    <li>
                        <a href="/Panel/ShowProducts">
                            محصولات
                        </a>
                    </li>
                </ul>
            </div>
        </li>

        <li class="sidebar-dropdown">
            <a href="#">
                <span class="pull-right">مالی</span>
                <span class="pull-left fa fa-money"></span>
            </a>
            <div class="sidebar-submenu">
                <ul>
                    <li>
                        <a href="/Panel/ShowCoupons">
                            کوپن ها
                        </a>
                    </li>
                    <li>
                        <a href="/Panel/BankCard">
                            حساب مالی
                        </a>
                    </li>
                </ul>
            </div>
        </li>

        <li class="sidebar-dropdown">
            <a href="#">
                <span class="pull-right">تنظیمات</span>
                <span class="pull-left fa fa-cogs"></span>
            </a>
            <div class="sidebar-submenu">
                <ul>
                    <li>
                        <a href="@Url.Action("ActivateSellerPanel", "Seller")">
                            فعالسازی حساب
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("StoreCompletor","Store")">
                            مشخصات فروشگاه
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("SendDocument","Seller")">
                            بارگزاری مدارک
                        </a>
                    </li>
                </ul>
            </div>
        </li>
    }
        
</ul>
</div>
<div class="sidebar-footer">

    @if (User.IsInRole("admin"))
    {
        <h3>@User.Claims.First(c=>c.Type == ClaimTypes.Role).Value</h3>
        <a href="/Admin/ShowBrands">
            <i class="fa fa-bell"></i>
            <span class="badge badge-pill badge-warning notification"></span>
        </a>
      
        <a href="#">
            <i class="fa fa-envelope"></i>
            <span class="badge badge-pill badge-warning notification">1</span>
        </a>

        <a href="#">
            <i class="fa fa-cog"></i>
            <span class="badge badge-pill badge-warning notification">5</span>
        </a>

        <a href="@Url.Action("logout","Account")">
            <i class="fa fa-power-off"></i>
        </a>
    }
    else
    {
        <a href="#">
            <i class="fa fa-bell"></i>
            <span class="badge badge-pill badge-warning notification">3</span>
        </a>

        <a href="#">
            <i class="fa fa-envelope"></i>
            <span class="badge badge-pill badge-warning notification">1</span>
        </a>

        <a href="#">
            <i class="fa fa-cog"></i>
            <span class="badge badge-pill badge-warning notification">5</span>
        </a>

        <a href="@Url.Action("logout","Account")">
            <i class="fa fa-power-off"></i>
        </a>
    }

</div>

</div>
</nav>

</div>
<div>
    @RenderBody()
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/ManualPannel.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
</body>

</html>